version: "3.4"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example
  quarkus-hello:
    image: guhilling/quarkus-hello:latest
    ports:
      - "8080:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - QUARKUS_PROFILE=dockercompose
    networks:
      - jaeger-example
    depends_on:
      - jaeger
  quarkus-world:
    image: guhilling/quarkus-world:latest
    ports:
      - "8081:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - QUARKUS_PROFILE=dockercompose
    networks:
      - jaeger-example
    depends_on:
      - jaeger

networks:
  jaeger-example: