# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI with Maven and Docker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build - Maven

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  docker:
    name: Publish - DockerHub

    runs-on: ubuntu-latest
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - name: Login to Docker Hub
      run: docker login -u guhilling -p ${{ secrets.DOCKERHUB }}
