# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI with Maven and Docker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build - Maven and Docker
    runs-on: ubuntu-latest
    env:
      HELLO_REPO: quay.io/ghilling/quarkus-hello:latest
      WORLD_REPO: quay.io/ghilling/quarkus-world:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Docker images
        run: |
          cd quarkus-hello
          docker build -f src/main/docker/Dockerfile -t ${HELLO_REPO} .
          docker save ${HELLO_REPO} -o /tmp/hello.tar
          cd ../quarkus-world
          docker build -f src/main/docker/Dockerfile -t ${WORLD_REPO} .
          docker save ${WORLD_REPO} -o /tmp/world.tar
      - name: Upload artifact world
        uses: actions/upload-artifact@v2
        with:
          name: world
          path: /tmp/world.tar
      - name: Upload artifact hello
        uses: actions/upload-artifact@v2
        with:
          name: hello
          path: /tmp/hello.tar

  publish:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    name: Publish Docker Hub
    needs: build
    runs-on: ubuntu-latest
    env:
      HELLO_REPO: quay.io/ghilling/quarkus-hello:latest
      WORLD_REPO: quay.io/ghilling/quarkus-world:latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: world
          path: /tmp
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hello
          path: /tmp
      - name: Load images
        run: |
          docker load --input /tmp/world.tar
          docker load --input /tmp/hello.tar
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Publish Docker image (hello)
        run: docker push ${HELLO_REPO}
      - name: Publish Docker image (world)
        run: docker push ${WORLD_REPO}
